### ISSUE TITLE
I can't open server SSH 

### ISSUE THREAD

**Issue by dumy** [VShawn/PRemoteM#114]
**Describe the bug**
Save server SSH
IP address yes
user and pasword yes
and port 22
And SAVE

I can't open this server, PremoteM stay freeze and close app. Only when start server SSH  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - PRemoteM Version 0.5.10.2

**Additional context**

	Fatal		System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at PRM.Core.Protocol.Putty.PuttyOptions.SaveToKittyRegistryTable()
   at PRM.Core.Protocol.Putty.Host.KittyHost.SetPuttySessionConfig()
   at PRM.Core.Protocol.Putty.Host.KittyHost.InitKitty()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at PRM.Core.Protocol.Putty.PuttyOptions.SaveToKittyRegistryTable()
   at PRM.Core.Protocol.Putty.Host.KittyHost.SetPuttySessionConfig()
   at PRM.Core.Protocol.Putty.Host.KittyHost.InitKitty()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

2021-04-23T11:52:21.6128905+03:00[ThreadId:0000000002]		Fatal		System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Hide()
   at PRM.App.CloseAllWindow()
   at PRM.App.OnUnhandledException(Exception e)
   at PRM.App.<>c.<InitExceptionHandle>b__17_1(Object o, UnobservedTaskExceptionEventArgs args)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Hide()
   at PRM.App.CloseAllWindow()
   at PRM.App.OnUnhandledException(Exception e)
   at PRM.App.<>c.<InitExceptionHandle>b__17_1(Object o, UnobservedTaskExceptionEventArgs args)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

**Comment by VShawn** [comment]
You are not allowed to write to the registry for ssh client, that's why it freeze.

can you try:
1. run as "admin"
2. or try this package and give me a log feed back

[PRemoteM 0.5.10.3-beta.zip](https://github.com/VShawn/PRemoteM/files/6364662/PRemoteM.0.5.10.3-beta.zip)

**Comment by dumy** [comment]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.5.10.3-beta`(EXE Release)|
|.NET Framework | `.NET Framework 4.8`    |
|CLR            | `4.0.30319.42000`       |
|OS             | `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)`                  |

## Error Info

Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

## Stack Trace

```
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at PRM.Core.DB.Dapper.DapperDb.OpenConnection(Nullable`1 type, String newConnectionString) in D:\DemoProject\PRemoteM\PRM.Core\DB\Dapper\DapperDb.cs:line 46
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath) in D:\DemoProject\PRemoteM\PRM.Core\Model\PrmContext.cs:line 36
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 236
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
2021-04-26T11:33:27.2077257+03:00[ThreadId:0000000001]		Debug		OrderServerList: IdAsc
2021-04-26T11:33:36.4638523+03:00[ThreadId:0000000004]		Debug		Check update.
2021-04-26T11:33:38.1871320+03:00[ThreadId:0000000003]		Debug		NamedPipeServerStream get: ActivateMe
2021-04-26T11:33:46.1047812+03:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1936, H = 1056, Child , 
2021-04-26T11:33:46.4847662+03:00[ThreadId:0000000001]		Debug		Start Conn: 172.24.5.240 - cmd(31741019) by host(66476022) with Tab(32142578)
2021-04-26T11:33:46.4847662+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1
2021-04-26T11:33:49.7395920+03:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1936, H = 1056, Child NaN, NaN
2021-04-26T11:33:52.5857846+03:00[ThreadId:0000000001]		Debug		Remove connectionId = 69_66476022 from tab(32142578)
2021-04-26T11:33:52.5887859+03:00[ThreadId:0000000001]		Debug		DelProtocolHost host(66476022)
2021-04-26T11:33:52.5907794+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 1
2021-04-26T11:33:52.6077963+03:00[ThreadId:0000000001]		Debug		Close tab(32142578)
2021-04-26T11:33:52.6243753+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 0
2021-04-26T11:34:18.8443294+03:00[ThreadId:0000000003]		Debug		NamedPipeServerStream get: ActivateMe
2021-04-26T11:34:20.2935696+03:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1936, H = 1056, Child , 
2021-04-26T11:34:20.3530842+03:00[ThreadId:0000000001]		Debug		Start Conn: 172.24.5.240 - cmd(31741019) by host(28090709) with Tab(50769665)
2021-04-26T11:34:20.3586418+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1
2021-04-26T11:34:23.9508037+03:00[ThreadId:0000000001]		Debug		Remove connectionId = 69_28090709 from tab(50769665)
2021-04-26T11:34:23.9538077+03:00[ThreadId:0000000001]		Debug		DelProtocolHost host(28090709)
2021-04-26T11:34:23.9558136+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 1
2021-04-26T11:34:23.9618139+03:00[ThreadId:0000000001]		Debug		Close tab(50769665)
2021-04-26T11:34:23.9816574+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 0
2021-04-26T11:34:25.8534226+03:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1936, H = 1056, Child , 
2021-04-26T11:34:25.9546735+03:00[ThreadId:0000000001]		Debug		Start Conn: 172.16.82.145 - test-Backup(16619954) by host(23128868) with Tab(43129175)
2021-04-26T11:34:25.9586745+03:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1
2021-04-26T11:34:26.0374948+03:00[ThreadId:0000000002]		Fatal		System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at PRM.Core.Protocol.Putty.PuttyOptions.SaveToKittyRegistryTable()
   at PRM.Core.Protocol.Putty.Host.KittyHost.SetPuttySessionConfig()
   at PRM.Core.Protocol.Putty.Host.KittyHost.InitKitty()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at PRM.Core.Protocol.Putty.PuttyOptions.SaveToKittyRegistryTable()
   at PRM.Core.Protocol.Putty.Host.KittyHost.SetPuttySessionConfig()
   at PRM.Core.Protocol.Putty.Host.KittyHost.InitKitty()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
2021-04-26T11:34:26.3150193+03:00[ThreadId:0000000002]		Fatal		System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Hide()
   at PRM.App.CloseAllWindow()
   at PRM.App.OnUnhandledException(Exception e)
   at PRM.App.<>c.<InitExceptionHandle>b__17_1(Object o, UnobservedTaskExceptionEventArgs args)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Hide()
   at PRM.App.CloseAllWindow()
   at PRM.App.OnUnhandledException(Exception e)
   at PRM.App.<>c.<InitExceptionHandle>b__17_1(Object o, UnobservedTaskExceptionEventArgs args)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
2021-04-26T11:34:27.2950268+03:00[ThreadId:0000000013]		Debug		ShowFolder(/, 0) START
2021-04-26T11:34:27.2970176+03:00[ThreadId:0000000013]		Debug		ShowFolder before ListDirectoryItems
2021-04-26T11:35:38.6475813+03:00[ThreadId:0000000001]		Debug		Call HideMe()
2021-04-26T11:35:38.7873503+03:00[ThreadId:0000000001]		Fatal		System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at PRM.Core.DB.Dapper.DapperDb.OpenConnection(Nullable`1 type, String newConnectionString) in D:\DemoProject\PRemoteM\PRM.Core\DB\Dapper\DapperDb.cs:line 46
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath) in D:\DemoProject\PRemoteM\PRM.Core\Model\PrmContext.cs:line 36
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 236
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at PRM.Core.DB.Dapper.DapperDb.OpenConnection(Nullable`1 type, String newConnectionString) in D:\DemoProject\PRemoteM\PRM.Core\DB\Dapper\DapperDb.cs:line 46
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath) in D:\DemoProject\PRemoteM\PRM.Core\Model\PrmContext.cs:line 36
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 236
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-04-26T11:35:38.9518927+03:00[ThreadId:0000000001]		Debug		Call HideMe()

```

</details>

**Comment by VShawn** [comment]
@dumy  sorry I forgot SQLite.Interop.dll

[Release.zip](https://github.com/VShawn/PRemoteM/files/6375543/Release.zip)

**Comment by dumy** [comment]
thanks, now it works
I'll buy you a coffee :D
