### ISSUE TITLE
installation from github zip, exe not working

### ISSUE THREAD

**Issue by devscheffer** [VShawn/PRemoteM#159]
**Describe the bug**
When I click on the exe file not is happening. It doesnt start the app.

**To Reproduce**
1. download de github zip
2. Click on premotem.exe
3. Nothing happens

**Expected behavior**
program to start.

**Desktop (please complete the following information):**
 - OS:Windows 10 Enterprise
 - PRemoteM Version 0.5.11.1

**Comment by jfbleach** [comment]
I am having the same issue:  Here is the log contents.
2021-11-15T09:56:16.0138634-08:00[ThreadId:0000000001]		Fatal		System.TypeInitializationException: The type initializer for 'PRM.App' threw an exception. ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(IEnumerable`1 enabledProviderNames, Boolean isCaseSensitive)
   at PRM.Core.Model.KeywordMatchService..ctor() in C:\projects\premotem-release-by-tag-automatically\PRM.Core\Model\KeywordMatchService.cs:line 48
   at PRM.Core.Model.PrmContext..ctor() in C:\projects\premotem-release-by-tag-automatically\PRM.Core\Model\PrmContext.cs:line 20
   at PRM.App..cctor() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 30
   --- End of inner exception stack trace ---
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 228
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 228
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2021-11-15T09:56:16.0854102-08:00[ThreadId:0000000001]		Fatal		System.TypeInitializationException: The type initializer for 'PRM.App' threw an exception. ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(IEnumerable`1 enabledProviderNames, Boolean isCaseSensitive)
   at PRM.Core.Model.KeywordMatchService..ctor() in C:\projects\premotem-release-by-tag-automatically\PRM.Core\Model\KeywordMatchService.cs:line 48
   at PRM.Core.Model.PrmContext..ctor() in C:\projects\premotem-release-by-tag-automatically\PRM.Core\Model\PrmContext.cs:line 20
   at PRM.App..cctor() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 30
   --- End of inner exception stack trace ---
   at PRM.App.get_Window() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 28
   at PRM.App.CloseAllWindow() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 320
   at PRM.App.OnUnhandledException(Exception e) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 39
   at PRM.App.<>c.<InitExceptionHandle>b__17_0(Object o, DispatcherUnhandledExceptionEventArgs args) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 61
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PRM.App.Main()
   at PRM.App.get_Window() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 28
   at PRM.App.CloseAllWindow() in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 320
   at PRM.App.OnUnhandledException(Exception e) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 39
   at PRM.App.<>c.<InitExceptionHandle>b__17_0(Object o, DispatcherUnhandledExceptionEventArgs args) in C:\projects\premotem-release-by-tag-automatically\PRemoteM\App.xaml.cs:line 61
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PRM.App.Main()

**Comment by jfbleach** [comment]
I was able to cure this but downloading https://docs.microsoft.com/en-us/sysinternals/downloads/streams
and running 
streams.exe -d -s *.*
In the PRemotMxxxxxx folder

**Comment by VShawn** [comment]
@jfbleach  thx for your solution
