### ISSUE TITLE
Exception while typing in a launcher search box

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#210]
<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM | `0.6.2-beta.2`(EXE Release)|
|.NET Framework | `.NET Framework 4.8`    |
|CLR            | `4.0.30319.42000`       |
|OS             | `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)`                  |

## InnerException Info

An item with the same key has already been added.

## InnerException Stack Trace

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.AppendDescriptions(MatchCache& matchCache)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.DoFindMatches(MatchCache matchCache, IEnumerable`1 keywords, IEnumerable`1 keywordsInTrueCase)
   at VariableKeywordMatcher.Interface.MatchProviderBase.DoMatches(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.<>c__DisplayClass6_0.<Match>b__0(MatchProviderBase provider)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at VariableKeywordMatcher.Matcher.Match(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.Matchs(List`1 matchCaches, IEnumerable`1 keywords)
   at PRM.Core.Service.KeywordMatchService.Match(List`1 originalStrings, IEnumerable`1 keywords) in D:\DemoProject\PRemoteM\PRM.Core\Service\KeywordMatchService.cs:line 131
   at PRM.Utils.Filters.TagAndKeywordFilter.MatchKeywords(ProtocolServerBase server, IEnumerable`1 tagFilters, IEnumerable`1 keyWords) in D:\DemoProject\PRemoteM\PRemoteM\Utils\Filters\TagAndKeywordFilter.cs:line 113
   at PRM.ViewModel.VmSearchBox.UpdateItemsList(String keyword) in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 253
   at PRM.ViewModel.VmSearchBox.<>c__DisplayClass28_0.<set_Filter>b__0() in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

## Error Info

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

## Stack Trace

```

```

## Recent Log 

```
2022-02-28T19:56:51.6612589+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T19:58:09.3796753+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:03:10.4465685+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:03:34.1294119+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:04:10.8150811+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:06:15.1660611+01:00[ThreadId:0000000029]		Debug		Check update.
2022-02-28T20:15:16.1775902+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:15:31.4934698+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:58:38.0466023+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T20:59:27.1816826+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T21:06:15.1668833+01:00[ThreadId:0000000009]		Debug		Check update.
2022-02-28T21:27:17.9188935+01:00[ThreadId:0000000001]		Debug		Resolution Changed: System.EventArgs
2022-02-28T21:35:38.0291256+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke launcher _isHidden = True
2022-02-28T21:35:42.9038783+01:00[ThreadId:0000000001]		Debug		Call HideMe()
2022-02-28T21:35:42.9108773+01:00[ThreadId:0000000001]		Debug		Call HideMe()
2022-02-28T21:35:42.9274410+01:00[ThreadId:0000000001]		Info		we don't have a custom protocol named: RDP!
2022-02-28T21:35:42.9805186+01:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1486, H = 864, Child , 
2022-02-28T21:35:43.0215208+01:00[ThreadId:0000000001]		Debug		AxMsRdpClient09Host: Status => Initializing
2022-02-28T21:35:43.0255210+01:00[ThreadId:0000000001]		Debug		RDP Host: _rdp.Dispose()
2022-02-28T21:35:43.0315182+01:00[ThreadId:0000000001]		Debug		RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()
2022-02-28T21:35:43.0365185+01:00[ThreadId:0000000001]		Debug		RDP Host: init CreateControl();
2022-02-28T21:35:43.1185180+01:00[ThreadId:0000000001]		Debug		RDP Host: init Static
2022-02-28T21:35:43.1235157+01:00[ThreadId:0000000001]		Debug		RDP Host: init conn bar
2022-02-28T21:35:43.1275198+01:00[ThreadId:0000000001]		Debug		RDP Host: init Redirect
2022-02-28T21:35:43.1335169+01:00[ThreadId:0000000001]		Debug		RDP Host: init Display with ScaleFactor = 100, W = 1482, H = 830
2022-02-28T21:35:43.1375192+01:00[ThreadId:0000000001]		Debug		RDP Host: Display init end: RDP.DesktopWidth = 1482, RDP.DesktopWidth = 1482,
2022-02-28T21:35:43.1415190+01:00[ThreadId:0000000001]		Debug		RDP Host: init Performance
2022-02-28T21:35:43.1445145+01:00[ThreadId:0000000001]		Debug		RdpInit: DisplayPerformance = High, flag = 110000000
2022-02-28T21:35:43.1475158+01:00[ThreadId:0000000001]		Debug		RDP Host: init Gateway
2022-02-28T21:35:43.1505161+01:00[ThreadId:0000000001]		Debug		AxMsRdpClient09Host: Status => Initialized
2022-02-28T21:35:43.1725148+01:00[ThreadId:0000000001]		Debug		AxMsRdpClient09Host: Status => Connecting
2022-02-28T21:35:43.6071481+01:00[ThreadId:0000000001]		Debug		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1
2022-02-28T21:35:44.4216069+01:00[ThreadId:0000000001]		Debug		RDP Host:  RdpOnOnConnected
2022-02-28T21:35:44.4256069+01:00[ThreadId:0000000001]		Debug		AxMsRdpClient09Host: Status => Connected
2022-02-28T21:35:47.0431629+01:00[ThreadId:0000000001]		Debug		RDP Host:  RdpOnOnLoginComplete
2022-02-28T21:35:48.0579293+01:00[ThreadId:0000000025]		Debug		RDP resize to: W = 1482, H = 830, ScaleFactor = 100
2022-02-28T21:35:48.8819335+01:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1874, H = 1096, Child NaN, NaN
2022-02-28T21:35:48.9717672+01:00[ThreadId:0000000001]		Debug		Tab size change to:W = 1874, H = 1096, Child NaN, NaN
2022-02-28T21:35:49.7209330+01:00[ThreadId:0000000015]		Debug		RDP resize to: W = 1858, H = 1050, ScaleFactor = 100
2022-02-28T21:35:53.0985976+01:00[ThreadId:0000000001]		Debug		DelProtocolHost: enter to delete host(id = 3)
2022-02-28T21:35:53.1075959+01:00[ThreadId:0000000001]		Debug		Remove connectionId = 3 from tab(28525238)
2022-02-28T21:35:53.1115960+01:00[ThreadId:0000000001]		Debug		DelProtocolHost: get host(52104579)
2022-02-28T21:35:53.1145932+01:00[ThreadId:0000000001]		Debug		DelProtocolHost: removed and now, ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 1
2022-02-28T21:35:53.1175919+01:00[ThreadId:0000000001]		Debug		RDP Host: _rdp.Dispose()
2022-02-28T21:35:53.1205916+01:00[ThreadId:0000000001]		Debug		CloseEmptyTabs: Closing tab(28525238)
2022-02-28T21:35:53.1311652+01:00[ThreadId:0000000001]		Debug		DelTabWindow: try to delete token = 637816809429314408
2022-02-28T21:35:53.1341641+01:00[ThreadId:0000000001]		Debug		DelTabWindow: try to delete token = 637816809429314408
2022-02-28T21:35:53.1391647+01:00[ThreadId:0000000001]		Debug		CloseEmptyTabs: Closed tab(28525238)ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 0
2022-02-28T21:35:54.5013503+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke launcher _isHidden = True
2022-02-28T21:35:58.1843828+01:00[ThreadId:0000000001]		Fatal		System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.AppendDescriptions(MatchCache& matchCache)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.DoFindMatches(MatchCache matchCache, IEnumerable`1 keywords, IEnumerable`1 keywordsInTrueCase)
   at VariableKeywordMatcher.Interface.MatchProviderBase.DoMatches(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.<>c__DisplayClass6_0.<Match>b__0(MatchProviderBase provider)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at VariableKeywordMatcher.Matcher.Match(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.Matchs(List`1 matchCaches, IEnumerable`1 keywords)
   at PRM.Core.Service.KeywordMatchService.Match(List`1 originalStrings, IEnumerable`1 keywords) in D:\DemoProject\PRemoteM\PRM.Core\Service\KeywordMatchService.cs:line 131
   at PRM.Utils.Filters.TagAndKeywordFilter.MatchKeywords(ProtocolServerBase server, IEnumerable`1 tagFilters, IEnumerable`1 keyWords) in D:\DemoProject\PRemoteM\PRemoteM\Utils\Filters\TagAndKeywordFilter.cs:line 113
   at PRM.ViewModel.VmSearchBox.UpdateItemsList(String keyword) in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 253
   at PRM.ViewModel.VmSearchBox.<>c__DisplayClass28_0.<set_Filter>b__0() in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.AppendDescriptions(MatchCache& matchCache)
   at VariableKeywordMatcher.Provider.ChineseZhCnPinYin.ChineseZhCnPinYinMatchProvider.DoFindMatches(MatchCache matchCache, IEnumerable`1 keywords, IEnumerable`1 keywordsInTrueCase)
   at VariableKeywordMatcher.Interface.MatchProviderBase.DoMatches(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.<>c__DisplayClass6_0.<Match>b__0(MatchProviderBase provider)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at VariableKeywordMatcher.Matcher.Match(MatchCache matchCache, IEnumerable`1 keywords)
   at VariableKeywordMatcher.Matcher.Matchs(List`1 matchCaches, IEnumerable`1 keywords)
   at PRM.Core.Service.KeywordMatchService.Match(List`1 originalStrings, IEnumerable`1 keywords) in D:\DemoProject\PRemoteM\PRM.Core\Service\KeywordMatchService.cs:line 131
   at PRM.Utils.Filters.TagAndKeywordFilter.MatchKeywords(ProtocolServerBase server, IEnumerable`1 tagFilters, IEnumerable`1 keyWords) in D:\DemoProject\PRemoteM\PRemoteM\Utils\Filters\TagAndKeywordFilter.cs:line 113
   at PRM.ViewModel.VmSearchBox.UpdateItemsList(String keyword) in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 253
   at PRM.ViewModel.VmSearchBox.<>c__DisplayClass28_0.<set_Filter>b__0() in D:\DemoProject\PRemoteM\PRemoteM\ViewModel\VmSearchBox.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

</details>

**Comment by VShawn** [comment]
I have encountered this bug, I didn't find the reason. But it disappear after I fix #212:

> I fix this in last commit yestday
_Originally posted by @VShawn in https://github.com/VShawn/PRemoteM/issues/212#issuecomment-1054847506_
