### ISSUE TITLE
Published version is missing SQLite Interop library

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#85]
## Environment
PRemoteM Ver: `0.5.9.2102191952`
OS: `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)`
.NET Framework: `.NET Framework 4.8`
CLR: `4.0.30319.42000`

## Error Info
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64

## Stack Trace
```
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 
2021-02-19T09:45:48.2804169+01:00[ThreadId:0000000001]		<font color=Green>Debug</font>		Resolution Change: System.EventArgs
2021-02-19T12:27:56.3106651+01:00[ThreadId:0000000001]		<font color=Green>Debug</font>		Call shortcut to invoke quick window.
2021-02-19T15:28:00.7130189+01:00[ThreadId:0000000001]		<font color=Green>Debug</font>		Call shortcut to invoke quick window.
2021-02-19T16:46:20.7001905+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal</font>**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-02-19T16:52:11.6959509+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal</font>**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by majkinetor** [comment]
Here is how it looks with above mentioned changes. I didn't remove HTML in stack trace but you should probably do that given that GH and GL do not allow it (not sure how Gitee does that). 

<details>

## Environment

|    **Software**    |                      **Version**                      |
| :-------------- | :------------------------------------------------- |
| PRemoteM | `0.5.9.2102191952`                                |
| .NET Framework | `.NET Framework 4.8`                              |
| CLR            | `4.0.30319.42000`                                 |
| OS             | `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)` |

## Error Info
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64

## Stack Trace

```
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
2021-02-19T09:45:48.2804169+01:00[ThreadId:0000000001]		Debug		Resolution Change: System.EventArgs
2021-02-19T12:27:56.3106651+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke quick window.
2021-02-19T15:28:00.7130189+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke quick window.
2021-02-19T16:46:20.7001905+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-02-19T16:52:11.6959509+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

</details>

**Comment by VShawn** [comment]
> BUG

confirm.  I missed `SQLite.Interop.dll` when it make a package. 

`SQLite.Interop.dll` is in my `SYSTEM PATH` that's why I did not aware I missed somethings when I test it.

I have update the release package, please try it and contact me if any other bug error occur

> why chinese

I dont know, the error was throw by https://github.com/dotnetcore/FreeSql, I change db module to it for  .NET Core compatibility And it should have English support.

>markdown

this will fix in next update, maybe we need create a ticket for it?

**Comment by VShawn** [comment]
FUXK ME, they are not offering English exception info for now. all exception info were written in static code by Chinese.

https://github.com/dotnetcore/FreeSql/blob/c12c5523525818abaa05b03d2dfd6ae70b6e7964/Providers/FreeSql.Provider.Sqlite/SqliteAdo/SqliteConnectionPool.cs#L193

should  we consider change another DB ORM component? any suggestions?

**Comment by majkinetor** [comment]
> FUXK ME, they are not offering English exception info for now. all exception info were written in static code by Chinese.

God damn people, when will they learn that only English is acceptable. I don't care which language either as long as the whole world uses one. 
 
> should we consider change another DB ORM component? any suggestions?

Let me take a look. I am huge sqlite fan :-) I usually forbid ORM on my projects - my team tested entity, daper etc. and slowdown is between 20% to 300%.  We need every bit of perf for web apps with mmlions of users  but this is desktop app so such slow down is not relevant.
