### ISSUE TITLE
Crashed when user who are using multi-screen in different scale factor and open a all screen & disabled RDGateway RDP session

### ISSUE THREAD

**Issue by waghelapritesh** [VShawn/PRemoteM#94]
## Environment

PRemoteM Ver: `0.5.9.2102191952`

OS: `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)`

.NET Framework: `.NET Framework 4.8`

CLR: `4.0.30319.42000`

## Error Info

Specified argument was out of the range of valid values.

## Stack Trace

```

   at PRM.Core.Protocol.RDP.ProtocolServerRDP.ToRdpConfig(PrmContext context) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\RDP\ProtocolServerRDP.cs:line 490

   at PRM.Model.RemoteWindowPool.ConnectRdpWithFullScreenByMstsc(ProtocolServerRDP rdp)

   at PRM.Model.RemoteWindowPool.ConnectWithFullScreen(VmProtocolServer vmProtocolServer)

   at PRM.Model.RemoteWindowPool.ShowRemoteHost(Int64 serverId, String assignTabToken)

   at PRM.Core.Protocol.VmProtocolServer.<get_CmdConnServer>b__31_0(Object o) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\VmProtocolServer.cs:line 97

   at Shawn.Utils.RelayCommand.Execute(Object parameter) in D:\DemoProject\PRemoteM\PRM.Core\Utils\RelayCommand.cs:line 44

   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)

   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Recent Log 

2021-03-08T22:16:27.7582238+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Display

2021-03-08T22:16:27.7738591+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Performance

2021-03-08T22:16:27.7758524+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RdpInit: DisplayPerformance = Auto, flag = 0

2021-03-08T22:16:27.7925390+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Gateway

2021-03-08T22:16:27.8075978+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Initialized

2021-03-08T22:16:27.8319330+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Connecting

2021-03-08T22:16:28.4238301+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Start Conn: z840-AD_Administrator(42336695) by host(36292894) with Tab(56087165)

2021-03-08T22:16:28.4397579+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1

2021-03-08T22:16:28.7709337+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host:  RdpOnOnConnected

2021-03-08T22:16:28.8005287+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Connected

2021-03-08T22:16:31.4021296+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host:  RdpOnOnLoginComplete

2021-03-08T22:16:43.6488728+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Tab size change to:W = 1552, H = 841, Child NaN, NaN

2021-03-08T22:16:52.6166412+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Tab size change to:W = 1382, H = 744, Child NaN, NaN

2021-03-08T22:16:52.8059060+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Tab size change to:W = 1382, H = 744, Child NaN, NaN

2021-03-08T22:17:03.3950699+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Remove connectionId = 19 from tab(56087165)

2021-03-08T22:17:03.4053124+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		DelProtocolHost host(36292894)

2021-03-08T22:17:03.4134332+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 1

2021-03-08T22:17:03.4241919+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: _rdp.Dispose()

2021-03-08T22:17:03.4545121+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: _rdp.Dispose()

2021-03-08T22:17:03.4808266+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Close tab(56087165)

2021-03-08T22:17:03.5084023+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 0

2021-03-08T22:17:08.0570468+05:30[ThreadId:0000000001]		<u>**<font color=Red>Fatal</font>**</u>		System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

   at PRM.Core.Protocol.RDP.ProtocolServerRDP.ToRdpConfig(PrmContext context) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\RDP\ProtocolServerRDP.cs:line 490

   at PRM.Model.RemoteWindowPool.ConnectRdpWithFullScreenByMstsc(ProtocolServerRDP rdp)

   at PRM.Model.RemoteWindowPool.ConnectWithFullScreen(VmProtocolServer vmProtocolServer)

   at PRM.Model.RemoteWindowPool.ShowRemoteHost(Int64 serverId, String assignTabToken)

   at PRM.Core.Protocol.VmProtocolServer.<get_CmdConnServer>b__31_0(Object o) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\VmProtocolServer.cs:line 97

   at Shawn.Utils.RelayCommand.Execute(Object parameter) in D:\DemoProject\PRemoteM\PRM.Core\Utils\RelayCommand.cs:line 44

   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)

   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at PRM.Core.Protocol.RDP.ProtocolServerRDP.ToRdpConfig(PrmContext context) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\RDP\ProtocolServerRDP.cs:line 490

   at PRM.Model.RemoteWindowPool.ConnectRdpWithFullScreenByMstsc(ProtocolServerRDP rdp)

   at PRM.Model.RemoteWindowPool.ConnectWithFullScreen(VmProtocolServer vmProtocolServer)

   at PRM.Model.RemoteWindowPool.ShowRemoteHost(Int64 serverId, String assignTabToken)

   at PRM.Core.Protocol.VmProtocolServer.<get_CmdConnServer>b__31_0(Object o) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\VmProtocolServer.cs:line 97

   at Shawn.Utils.RelayCommand.Execute(Object parameter) in D:\DemoProject\PRemoteM\PRM.Core\Utils\RelayCommand.cs:line 44

   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)

   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2021-03-08T22:17:19.1260050+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		OrderServerList: Name

2021-03-08T22:17:24.7248220+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Tab size change to:W = 1382, H = 744, Child , 

2021-03-08T22:17:24.9100140+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Initializing

2021-03-08T22:17:24.9220173+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: _rdp.Dispose()

2021-03-08T22:17:24.9379702+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init new AxMsRdpClient9NotSafeForScriptingEx()

2021-03-08T22:17:24.9671774+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init CreateControl();

2021-03-08T22:17:25.0663739+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init server info

2021-03-08T22:17:25.0910340+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Static

2021-03-08T22:17:25.1061103+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init conn bar

2021-03-08T22:17:25.1193961+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Redirect

2021-03-08T22:17:25.1329063+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Display

2021-03-08T22:17:25.1452081+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Performance

2021-03-08T22:17:25.1561969+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RdpInit: DisplayPerformance = Auto, flag = 0

2021-03-08T22:17:25.1676258+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: init Gateway

2021-03-08T22:17:25.1787010+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Initialized

2021-03-08T22:17:25.2016237+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		AxMsRdpClient09Host: Status => Connecting

2021-03-08T22:17:25.9759964+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Start Conn: win19-veeam(61202487) by host(13951479) with Tab(22646572)

2021-03-08T22:17:25.9869358+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 1, FullWin.Count = 0, _tabWindows.Count = 1

2021-03-08T22:17:27.7328224+05:30[ThreadId:0000000006]		<font color=Green>Debug</font>		Check update.

2021-03-08T22:17:28.0886130+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Remove connectionId = 26 from tab(22646572)

2021-03-08T22:17:28.1045718+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		DelProtocolHost host(13951479)

2021-03-08T22:17:28.1215247+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 1

2021-03-08T22:17:28.1414735+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: _rdp.Dispose()

2021-03-08T22:17:28.1669272+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		Close tab(22646572)

2021-03-08T22:17:28.1975847+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		ProtocolHosts.Count = 0, FullWin.Count = 0, _tabWindows.Count = 0

2021-03-08T22:17:28.2303603+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host: RdpOnDisconnected

2021-03-08T22:18:05.8847132+05:30[ThreadId:0000000001]		<font color=Green>Debug</font>		OrderServerList: Name

2021-03-08T22:18:07.7110469+05:30[ThreadId:0000000001]		<u>**<font color=Red>Fatal</font>**</u>		System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

   at PRM.Core.Protocol.RDP.ProtocolServerRDP.ToRdpConfig(PrmContext context) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\RDP\ProtocolServerRDP.cs:line 490

   at PRM.Model.RemoteWindowPool.ConnectRdpWithFullScreenByMstsc(ProtocolServerRDP rdp)

   at PRM.Model.RemoteWindowPool.ConnectWithFullScreen(VmProtocolServer vmProtocolServer)

   at PRM.Model.RemoteWindowPool.ShowRemoteHost(Int64 serverId, String assignTabToken)

   at PRM.Core.Protocol.VmProtocolServer.<get_CmdConnServer>b__31_0(Object o) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\VmProtocolServer.cs:line 97

   at Shawn.Utils.RelayCommand.Execute(Object parameter) in D:\DemoProject\PRemoteM\PRM.Core\Utils\RelayCommand.cs:line 44

   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)

   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at PRM.Core.Protocol.RDP.ProtocolServerRDP.ToRdpConfig(PrmContext context) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\RDP\ProtocolServerRDP.cs:line 490

   at PRM.Model.RemoteWindowPool.ConnectRdpWithFullScreenByMstsc(ProtocolServerRDP rdp)

   at PRM.Model.RemoteWindowPool.ConnectWithFullScreen(VmProtocolServer vmProtocolServer)

   at PRM.Model.RemoteWindowPool.ShowRemoteHost(Int64 serverId, String assignTabToken)

   at PRM.Core.Protocol.VmProtocolServer.<get_CmdConnServer>b__31_0(Object o) in D:\DemoProject\PRemoteM\PRM.Core\Protocol\VmProtocolServer.cs:line 97

   at Shawn.Utils.RelayCommand.Execute(Object parameter) in D:\DemoProject\PRemoteM\PRM.Core\Utils\RelayCommand.cs:line 44

   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)

   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by VShawn** [comment]
Thanks for reporting the issue. 

@waghelapritesh As a temporary solution you can set Gateway to `Automatically detect`, then it should work.

It is easy to locate why it was crashed, this bug only occur when user using multi-screen in different scale factor.

https://github.com/VShawn/PRemoteM/blob/3fb9dac7581983cc5b112d31f413a7ac93cf136f/PRM.Core/Protocol/RDP/ProtocolServerRDP.cs#L488-L491
