### ISSUE TITLE
Crash with 0.5.10 - The module was expected to contain an assembly manifest

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#99]
Fails to start, dies silently and this is from Event Viewer.

```
Faulting application name: PRemoteM.exe, version: 1.0.0.0, time stamp: 0xbcf727d1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0xb610d74d
Exception code: 0xe0434352
Fault offset: 0x0012a8b2
Faulting process id: 0x42ac
Faulting application start time: 0x01d721739627af24
Faulting application path: C:\tools\PRemoteM\PRemoteM.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8632bc51-314c-4b68-99dd-851117e369fa
Faulting package full name: 
Faulting package-relative application ID: 

---

Application: PRemoteM.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at PRM.Core.Model.KeywordMatchService..ctor()
   at PRM.Core.Model.PrmContext..ctor()
   at PRM.App..cctor()

Exception Info: System.TypeInitializationException
   at PRM.App.get_Window()
   at PRM.App.CloseAllWindow()
   at PRM.App.OnUnhandledException(System.Exception)
   at PRM.App+<>c.<InitExceptionHandle>b__17_2(System.Object, System.UnhandledExceptionEventArgs)


```
This is from log in Roaming:

```
2021-03-25T13:40:24.9657123+01:00[ThreadId:0000000001]		Fatal		System.TypeInitializationException: The type initializer for 'PRM.App' threw an exception. ---> System.BadImageFormatException: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(IEnumerable`1 enabledProviderNames, Boolean isCaseSensitive)
   at PRM.Core.Model.KeywordMatchService..ctor() in D:\DemoProject\PRemoteM\PRM.Core\Model\KeywordMatchService.cs:line 48
   at PRM.Core.Model.PrmContext..ctor() in D:\DemoProject\PRemoteM\PRM.Core\Model\PrmContext.cs:line 20
   at PRM.App..cctor() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 30
   --- End of inner exception stack trace ---
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 228
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 228
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2021-03-25T13:40:24.9817124+01:00[ThreadId:0000000001]		Fatal		System.TypeInitializationException: The type initializer for 'PRM.App' threw an exception. ---> System.BadImageFormatException: The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(IEnumerable`1 enabledProviderNames, Boolean isCaseSensitive)
   at PRM.Core.Model.KeywordMatchService..ctor() in D:\DemoProject\PRemoteM\PRM.Core\Model\KeywordMatchService.cs:line 48
   at PRM.Core.Model.PrmContext..ctor() in D:\DemoProject\PRemoteM\PRM.Core\Model\PrmContext.cs:line 20
   at PRM.App..cctor() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 30
   --- End of inner exception stack trace ---
   at PRM.App.get_Window() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 28
   at PRM.App.CloseAllWindow() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 322
   at PRM.App.OnUnhandledException(Exception e) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 39
   at PRM.App.<>c.<InitExceptionHandle>b__17_0(Object o, DispatcherUnhandledExceptionEventArgs args) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 61
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PRM.App.Main()
   at PRM.App.get_Window() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 28
   at PRM.App.CloseAllWindow() in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 322
   at PRM.App.OnUnhandledException(Exception e) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 39
   at PRM.App.<>c.<InitExceptionHandle>b__17_0(Object o, DispatcherUnhandledExceptionEventArgs args) in D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:line 61
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at PRM.App.Main()
```

**Comment by VShawn** [comment]
strange, it works good on my dev-PC

I pre-release the 0.5.10 before find out what happen.

**Comment by majkinetor** [comment]
Thats why your dev-PC [isn't relevant](https://rlv.zcache.com/works_on_my_machine_classic_round_sticker-r56ce1cc314be46efbe749e9c58c761d5_v9waf_8byvr_630.jpg?view_padding=[285%2C0%2C285%2C0]) :)

**Comment by VShawn** [comment]
and it works with my server
![image](https://user-images.githubusercontent.com/10143738/112476060-74e52e00-8dac-11eb-8530-8513f20089df.png)

**Comment by majkinetor** [comment]
Mhm... OK, then it must be me, will dig in dipper

**Comment by VShawn** [comment]
it seems you are the only one can reproduce the issue, let me know if you find any news. 

I am busy now, will back online after about 1.5 hour.

**Comment by VShawn** [comment]
error log show it came form `KeywordMatchService.cs:line 48`
it was the new Keyword module, you can try to delete the plug-in:
![image](https://user-images.githubusercontent.com/10143738/112477456-fe493000-8dad-11eb-9c3a-b308dbd927f3.png)

**Comment by majkinetor** [comment]
OK, I deleted entire folder - I install via `choco update` and it writes over existing folder. It now starts, but doesn't read my db file from that folder as before, I need to copy it to Roamning, although the created shortcut has correct folder set:

![image](https://user-images.githubusercontent.com/85767/112477732-98d84d80-8d73-11eb-8c81-c690345fcb6b.png)


It seems that portability is wrong, maybe related to #67

**Comment by majkinetor** [comment]
Ah, nvm ignore that, forgot to copy old ini.
